# Specify this if you want to use wandb
wandb:
  user: "koala_penguin"
  # Wandb checkpoint base directory
  base: "../data/output/Scannet/NKSR"
  # Optional upload path
  upload: "<REMOTE>:<PATH>"
  wname: ScanNet_Voxel-0.02_run_1

# Specify this if you want to use tensorboard
tb:
  # Checkpoint base directory
  base: "./tb/"
  upload: "<REMOTE>:<PATH>"

# Path where inference results will be saved
test_path: "./test/"
